version: '3.8'

name: snippetbox

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: snippetbox
      MYSQL_PASSWORD: snippetbox
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
